nhirokinet/bluelineconsole

- .gitignore
- .idea/gradle.xml
- .idea/misc.xml
- .idea/modules.xml
- .idea/runConfigurations.xml
- .idea/vcs.xml
- app/build.gradle
- app/src/main/AndroidManifest.xml
- app/src/main/java/net/nhiroki/bluelineconsole/applicationMain/MainActivity.java
- app/src/main/java/net/nhiroki/bluelineconsole/applicationMain/StartUpHelpActvity.java
- app/src/main/res/layout/activity_main.xml
- app/src/main/res/layout/activity_start_up_help_actvity.xml
- UI adjustment for tablets and landscape mode in small devices
- Support Android 5.1
> Version 1.0.2

- app/build.gradle
- app/src/main/java/net/nhiroki/bluelineconsole/applicationMain/MainActivity.java
> Version 1.0.3

- .idea/codeStyles/Project.xml
- .idea/gradle.xml
- .idea/misc.xml
- .idea/modules.xml
- app/build.gradle
- app/src/androidTest/java/net/nhiroki/bluelineconsole/calculator/CalculatorTest.java
- app/src/main/java/net/nhiroki/bluelineconsole/applicationMain/AppNotification.java
- app/src/main/java/net/nhiroki/bluelineconsole/applicationMain/MainActivity.java
- app/src/main/java/net/nhiroki/bluelineconsole/applicationMain/PreferencesActivity.java
- app/src/main/java/net/nhiroki/bluelineconsole/applicationMain/StartUpHelpActvity.java
- app/src/main/java/net/nhiroki/bluelineconsole/commandSearchers/CalculatorCommandSearcher.java
- app/src/main/java/net/nhiroki/bluelineconsole/commandSearchers/DateCommandSearcher.java
- app/src/main/java/net/nhiroki/bluelineconsole/commands/help/HelpCandidateEntry.java
- app/src/main/res/layout/activity_main.xml
- app/src/main/res/layout/activity_start_up_help_actvity.xml
- app/src/main/res/layout/preferences_activity_view.xml
- build.gradle
- gradle.properties
- gradle/wrapper/gradle-wrapper.properties
- out-of-source-resources/bluelineconsole.svg
> version 1.0.4

- app/build.gradle
- app/src/main/AndroidManifest.xml
- app/src/main/res/layout/activity_main.xml
> Version 1.0.6: open software keyboard immediately after launch

- app/src/main/java/net/nhiroki/bluelineconsole/applicationMain/PreferencesCustomWebActivity.java
- app/src/main/java/net/nhiroki/bluelineconsole/applicationMain/PreferencesEachURLActivity.java
- app/src/main/java/net/nhiroki/bluelineconsole/commandSearchers/ApplicationCommandSearcher.java
- app/src/main/java/net/nhiroki/bluelineconsole/commandSearchers/SearchEngineCommandSearcher.java
- app/src/main/java/net/nhiroki/bluelineconsole/commands/applications/ApplicationDatabase.java
- app/src/main/java/net/nhiroki/bluelineconsole/dataStore/cache/ApplicationInformation.java
- app/src/main/java/net/nhiroki/bluelineconsole/dataStore/cache/ApplicationInformationCache.java
- app/src/main/java/net/nhiroki/bluelineconsole/dataStore/persistent/URLEntry.java
- app/src/main/java/net/nhiroki/bluelineconsole/dataStore/persistent/URLPreferences.java
> Cases of package name

- app/src/main/java/net/nhiroki/bluelineconsole/applicationMain/CommandSearchAggregator.java
- app/src/main/java/net/nhiroki/bluelineconsole/applicationMain/PreferencesFragment.java
- app/src/main/java/net/nhiroki/bluelineconsole/commandSearchers/SearchEngineDefaultCommandSearcher.java
- app/src/main/java/net/nhiroki/bluelineconsole/commands/netutils/PingActivity.java
- app/src/main/java/net/nhiroki/bluelineconsole/commands/urls/WebSearchEngine.java
- app/src/main/java/net/nhiroki/bluelineconsole/commands/urls/WebSearchEnginesDatabase.java
- app/src/main/java/net/nhiroki/bluelineconsole/dataStore/persistent/URLEntry.java
- app/src/main/res/layout/main_activity_body.xml
- app/src/main/res/layout/preferences_custom_web_each_body.xml
- app/src/main/res/values-ja/strings.xml
- app/src/main/res/values/strings.xml
- app/src/main/res/xml/preferences.xml
- gradle/wrapper/gradle-wrapper.properties
Always add specific search engine at bottom of result
> Add default search engine

- .idea/misc.xml
- app/src/main/java/net/nhiroki/bluelineconsole/applicationMain/BaseWindowActivity.java
- app/src/main/java/net/nhiroki/bluelineconsole/applicationMain/CandidateListAdapter.java
- app/src/main/java/net/nhiroki/bluelineconsole/applicationMain/PreferencesCustomWebActivity.java
- app/src/main/java/net/nhiroki/bluelineconsole/applicationMain/PreferencesEachURLActivity.java
- app/src/main/java/net/nhiroki/bluelineconsole/commandSearchers/ApplicationCommandSearcher.java
- app/src/main/java/net/nhiroki/bluelineconsole/commands/urls/WebSearchEnginesDatabase.java
- app/src/main/res/layout/preferences_activity_body.xml
Behavior not changed except one bug of Wikipedia language selection (same bug with #40 in another place)
> Code cleanup 2021/1/11 part 2

- app/src/main/res/layout/main_activity_body.xml
flagForceAscii may not be a best choice, but for now I don't make change at 1.0.10 -> 1.0.11. Reverting to same option as 1.0.10.
> revert flagForceAscii

- app/build.gradle
- app/src/androidTest/java/net/nhiroki/bluelineconsole/calculator/CalculatorTest.java
- app/src/main/AndroidManifest.xml
- app/src/main/java/net/nhiroki/bluelineconsole/applicationMain/AppNotification.java
- app/src/main/java/net/nhiroki/bluelineconsole/applicationMain/BaseWindowActivity.java
- app/src/main/java/net/nhiroki/bluelineconsole/applicationMain/BootReceiver.java
- app/src/main/java/net/nhiroki/bluelineconsole/applicationMain/CandidateListAdapter.java
- app/src/main/java/net/nhiroki/bluelineconsole/applicationMain/MainActivity.java
- app/src/main/java/net/nhiroki/bluelineconsole/applicationMain/PreferencesActivity.java
- app/src/main/java/net/nhiroki/bluelineconsole/applicationMain/PreferencesEachURLActivity.java
- app/src/main/java/net/nhiroki/bluelineconsole/applicationMain/PreferencesFragment.java
- app/src/main/java/net/nhiroki/bluelineconsole/applicationMain/StartUpHelpActivity.java
- app/src/main/java/net/nhiroki/bluelineconsole/commands/applications/ApplicationDatabase.java
- app/src/main/java/net/nhiroki/bluelineconsole/commands/calculator/Calculator.java
- app/src/main/java/net/nhiroki/bluelineconsole/commands/calculator/CalculatorNumber.java
- app/src/main/java/net/nhiroki/bluelineconsole/commands/calculator/Operator.java
- app/src/main/java/net/nhiroki/bluelineconsole/commands/urls/WebSearchEngine.java
- app/src/main/java/net/nhiroki/bluelineconsole/commands/urls/WebSearchEnginesDatabase.java
- app/src/main/res/layout/candidateentryview.xml
- app/src/main/res/layout/preferences_custom_web_each_body.xml
- app/src/main/res/values/colors.xml
- app/src/main/res/values/dimens.xml
- app/src/main/res/xml/preferences.xml
- Stop using deprecated APIs
- Some cleanup
> clean up codes

- app/src/main/java/net/nhiroki/bluelineconsole/applicationMain/MainActivity.java
- app/src/main/res/layout/main_activity_body.xml
- app/src/main/res/layout/start_up_help_body.xml
- app/src/main/res/values/colors.xml
- app/src/main/res/values/styles.xml
multithread bug occured while testing theme, a little bit theme fix
> small bug fixes

- app/src/main/java/net/nhiroki/bluelineconsole/applicationMain/PreferencesActivity.java
- app/src/main/java/net/nhiroki/bluelineconsole/applicationMain/PreferencesCustomWebActivity.java
- app/src/main/java/net/nhiroki/bluelineconsole/applicationMain/PreferencesEachURLActivity.java
- app/src/main/java/net/nhiroki/bluelineconsole/applicationMain/PreferencesFragment.java
- app/src/main/java/net/nhiroki/bluelineconsole/applicationMain/StartUpHelpActivity.java
- app/src/main/java/net/nhiroki/bluelineconsole/commandSearchers/ApplicationCommandSearcher.java
- app/src/main/java/net/nhiroki/bluelineconsole/commandSearchers/PreferencesCommandSearcher.java
- app/src/main/java/net/nhiroki/bluelineconsole/commandSearchers/SearchEngineCommandSearcher.java
- app/src/main/java/net/nhiroki/bluelineconsole/commandSearchers/SearchEngineDefaultCommandSearcher.java
- app/src/main/java/net/nhiroki/bluelineconsole/commandSearchers/lib/StringMatchStrategy.java
- app/src/main/java/net/nhiroki/bluelineconsole/commands/netutils/Ping6Activity.java
- app/src/main/java/net/nhiroki/bluelineconsole/commands/netutils/PingActivity.java
- app/src/main/java/net/nhiroki/bluelineconsole/dataStore/persistent/URLEntry.java
- app/src/main/res/layout/preferences_custom_web_body.xml
- app/src/main/res/layout/preferences_custom_web_each_body.xml
- app/src/main/res/layout/start_up_help_body.xml
- app/src/main/res/layout/url_entry_view.xml
- app/src/main/res/values-ja/strings.xml
- app/src/main/res/values-zh-rCN/strings.xml
- app/src/main/res/values/strings.xml
- app/src/main/res/xml/preferences.xml
strings.xml was messed up, even English and Japanese had different ordering.
Make sections, order in a same way (1st commit), and labeled better names (2nd commit).
> Cleanup arrangement of strings.xml

- app/src/main/res/values-ja/strings.xml
- app/src/main/res/values-zh-rCN/strings.xml
- app/src/main/res/values/strings.xml
- app/src/main/res/xml/preferences.xml
It seems generally Locale Hint is better
> Swap option orders of Locale Hint and flagForceAscii

- app/src/main/java/net/nhiroki/bluelineconsole/dataStore/persistent/URLEntry.java
- app/src/main/res/layout/preferences_custom_web_each_body.xml
- app/src/main/res/values-ja/strings.xml
- app/src/main/res/values-zh-rCN/strings.xml
- app/src/main/res/values/strings.xml
At least program works, so it is up to user.
> command name can accept arbitary character

- app/build.gradle
Incrementing minor version because default behavior about IME is changed.
> Bump version to 1.2.0

- app/src/main/java/net/nhiroki/bluelineconsole/applicationMain/MainActivity.java
Adding header didn't show header as position 0.
> Show always top when input refreshed

- app/src/main/java/net/nhiroki/bluelineconsole/applicationMain/BaseWindowActivity.java
- app/src/main/java/net/nhiroki/bluelineconsole/applicationMain/CandidateListAdapter.java
- app/src/main/java/net/nhiroki/bluelineconsole/applicationMain/MainActivity.java
- app/src/main/java/net/nhiroki/bluelineconsole/commandSearchers/ApplicationCommandSearcher.java
- app/src/main/java/net/nhiroki/bluelineconsole/commandSearchers/NetUtilCommandSearcher.java
- app/src/main/java/net/nhiroki/bluelineconsole/commandSearchers/PreferencesCommandSearcher.java
- app/src/main/java/net/nhiroki/bluelineconsole/commandSearchers/SearchEngineCommandSearcher.java
- app/src/main/java/net/nhiroki/bluelineconsole/commandSearchers/SearchEngineDefaultCommandSearcher.java
- app/src/main/java/net/nhiroki/bluelineconsole/commandSearchers/URICommandSearcher.java
- app/src/main/java/net/nhiroki/bluelineconsole/interfaces/EventLauncher.java
Fixed some buggy behavior. Now all suspicious behavior I already found should be fixed.
But widget behavior looks complicated. so keeping widget feature experimental for now...
> Improve home and widget behavior

- app/src/main/java/net/nhiroki/bluelineconsole/applicationMain/MainActivity.java
As the documentation it is accepting dip unit. Currently I have no reason to doubt.
> Use correct unit for updateAppWidgetSize

- app/build.gradle
> Increment version code

- app/src/main/java/net/nhiroki/bluelineconsole/applicationMain/MainActivity.java
- not to updateAppWidgetSize() with size 0
- invalidate after updateAppWidgetSize() to force redraw
> Improve widget behavior

- app/src/main/java/net/nhiroki/bluelineconsole/applicationMain/BaseWindowActivity.java
- app/src/main/java/net/nhiroki/bluelineconsole/applicationMain/CandidateListAdapter.java
- app/src/main/java/net/nhiroki/bluelineconsole/applicationMain/HomeActivity.java
- app/src/main/java/net/nhiroki/bluelineconsole/applicationMain/MainActivity.java
- app/src/main/java/net/nhiroki/bluelineconsole/applicationMain/NotificationMigrationLostActivity.java
- app/src/main/java/net/nhiroki/bluelineconsole/applicationMain/PreferencesAccentColorActivity.java
- app/src/main/java/net/nhiroki/bluelineconsole/applicationMain/PreferencesActivity.java
- app/src/main/java/net/nhiroki/bluelineconsole/applicationMain/PreferencesCustomWebActivity.java
- app/src/main/java/net/nhiroki/bluelineconsole/applicationMain/PreferencesEachURLActivity.java
- app/src/main/java/net/nhiroki/bluelineconsole/applicationMain/PreferencesFragment.java
- app/src/main/java/net/nhiroki/bluelineconsole/applicationMain/PreferencesHomeScreenAddWidgetActivity.java
- app/src/main/java/net/nhiroki/bluelineconsole/applicationMain/PreferencesHomeScreenEachDefaultItemCommandActivity.java
- app/src/main/java/net/nhiroki/bluelineconsole/applicationMain/PreferencesHomeScreenEachWidgetActivity.java
- app/src/main/java/net/nhiroki/bluelineconsole/applicationMain/PreferencesHomeScreenItemsActivity.java
- app/src/main/java/net/nhiroki/bluelineconsole/applicationMain/PreferencesWidgetCommandEachActivity.java
- app/src/main/java/net/nhiroki/bluelineconsole/applicationMain/PreferencesWidgetCommandSelectWidget.java
- app/src/main/java/net/nhiroki/bluelineconsole/applicationMain/PreferencesWidgetCommandsActivity.java
- app/src/main/java/net/nhiroki/bluelineconsole/applicationMain/StartUpHelpActivity.java
- app/src/main/java/net/nhiroki/bluelineconsole/commandSearchers/eachSearcher/ApplicationCommandSearcher.java
- app/src/main/java/net/nhiroki/bluelineconsole/commandSearchers/eachSearcher/ContactSearchCommandSearcher.java
- app/src/main/java/net/nhiroki/bluelineconsole/commandSearchers/eachSearcher/NetUtilCommandSearcher.java
- app/src/main/java/net/nhiroki/bluelineconsole/commandSearchers/eachSearcher/PreferencesCommandSearcher.java
- app/src/main/java/net/nhiroki/bluelineconsole/commandSearchers/eachSearcher/SearchEngineCommandSearcher.java
- app/src/main/java/net/nhiroki/bluelineconsole/commandSearchers/eachSearcher/URICommandSearcher.java
- app/src/main/java/net/nhiroki/bluelineconsole/interfaces/EventLauncher.java
- app/src/main/res/xml/preferences.xml
- Show app name and version on config
- Refactor not to override onStop on BaseWindowActivity and calling originalOnStop on child
- Refactor EventLauncher to accept MainActivity directly
- MainActivity not to finish while assistant app in config
> Misc behavior improvement

- app/src/main/java/net/nhiroki/bluelineconsole/applicationMain/AppNotification.java
- app/src/main/java/net/nhiroki/bluelineconsole/widget/LauncherWidgetProvider.java
Android SDK 31 and Android 12 requires explicit FLAG_MUTABLE or
FLAG_IMMUTABLE flag.
> Add FLAG_MUTABLE to PendingIntent.getActivities

- app/src/main/AndroidManifest.xml
- app/src/main/java/net/nhiroki/bluelineconsole/applicationMain/MainActivity.java
Add intent-filter for share text to blueline console
> Add intent-filter for share text to blueline console 

- app/build.gradle
This can still run build scripts, as this is just report issue
> lintOptions ignoreWarnings to false

- app/src/main/java/net/nhiroki/bluelineconsole/applicationMain/theming/AppTheme.java
But I think middle-button paste on Linux-friendly systems leads just mistakes and not good...
> Remove unintended copy

- app/src/main/res/values/styles.xml
https://github.com/nhirokinet/bluelineconsole/issues/358
> Set android:windowOptOutEdgeToEdgeEnforcement to true

- fastlane/metadata/android/en-US/full_description.txt
- fastlane/metadata/android/ja/full_description.txt
- fastlane/metadata/android/ko-KR/full_description.txt
- fastlane/metadata/android/zh-CN/full_description.txt
- fastlane/metadata/android/zh-TW/full_description.txt
Source code link already exists in F-Droid UI but it is inconvenient to paste to Google Play
I will not care duplication
> add link to source code in fastlane files too
